name: Build and Update Version

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install custom JAR lib-utils
        run: |
          mvn install:install-file \
            -Dfile=./local-dependencies/Lib-Utils-1.1.2.jar \
            -DgroupId=com.georgejrdev \
            -DartifactId=lib-utils \
            -Dversion=1.1.2 \
            -Dpackaging=jar

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' 
          distribution: 'temurin'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Build with Maven
        run: mvn clean package

      - name: Extract Version from POM
        id: extract_version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project version: $version"
          echo "::set-output name=version::$version"

      - name: Rename JAR to SuperToolKit.jar
        run: |
          mv target/*-with-dependencies.jar SuperToolKit.jar
          echo "Renamed JAR to: SuperToolKit.jar"

      - name: Create linux<version> directory and copy files
        run: |
          version=${{ steps.extract_version.outputs.version }}
          dir_name="linux${version}"
          mkdir $dir_name
          cp SuperToolKit.jar $dir_name/
          cp ./scripts/install.sh $dir_name/
          cp ./scripts/stk.sh $dir_name/
          echo "Copied JAR and scripts to $dir_name"

      - name: Compress linux<version> to ZIP
        run: |
          version=${{ steps.extract_version.outputs.version }}
          dir_name="linux${version}"
          zip -r "${dir_name}.zip" $dir_name
          echo "Compressed $dir_name to ${dir_name}.zip"

      - name: Create build directory
        run: mkdir -p ./build

      - name: Move ZIP to build directory
        run: |
          version=${{ steps.extract_version.outputs.version }}
          mv linux${version}.zip ./build/
          echo "Moved linux${version}.zip to ./build/"

      - name: Remove SuperToolKit.jar from root
        run: |
          rm -f SuperToolKit.jar
          echo "Deleted SuperToolKit.jar from root directory"

      - name: Delete linux<version> directory
        run: |
          version=${{ steps.extract_version.outputs.version }}
          rm -rf linux${version}
          echo "Deleted linux${version} directory"

      - name: Update README.md with new version
        run: |
          version=${{ steps.extract_version.outputs.version }}
          sed -i "s/[0-9]\+\.[0-9]\+\.[0-9]\+/$version/g" README.md
          sed -i "s/SuperToolKit-[0-9]\+\.[0-9]\+\.[0-9]\+\.jar/SuperToolKit.jar/g" README.md

      - name: Commit and push changes
        run: |
          version=${{ steps.extract_version.outputs.version }}
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md build/
          git commit -m "Build - version: ${version}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}